add docker
Leanchers/online-book-store pull request #13
Opened 2024-09-12 14:13 UTC by Leanchers

2024-09-13 18:30 UTC, okuzan requested changes

2024-09-13 18:30 UTC, okuzan commented on docker-compose.yml
> +      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
```suggestion
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:${DEBUG_PORT}"

```

2024-09-13 18:30 UTC, okuzan commented on .env
> +DEBUG_PORT=5005
let's add .env to .gitignore
rename this file to .env.sample
actual .env should never be in source control, it's supposed to contain secrets

2024-09-14 06:10 UTC, Elena-Bruyako requested changes

2024-09-14 06:10 UTC, Elena-Bruyako commented on .env.sample
> +MYSQLDB_USER=root
```suggestion
MYSQLDB_USER=
```

remove other properties, it should be like template

2024-09-14 06:10 UTC, Elena-Bruyako commented on .env.sample
> +DEBUG_PORT=5005
Remove .env file

2024-09-14 12:05 UTC, okuzan approved these changes

2024-09-19 11:14 UTC, merged