Add book tests
Leanchers/online-book-store pull request #14
Opened 2024-10-13 03:07 UTC by Leanchers

![image](https://github.com/user-attachments/assets/9982559a-4e2c-413c-8e2d-515231ab65ce)

2024-10-14 10:14 UTC, JJJazl requested changes

2024-10-14 10:14 UTC, JJJazl commented on src/test/java/mate/academy/onlinebookstore/repository/BookRepositoryTest.java
> +        List<Book> actual = bookRepository.findAllByCategoryId(pageable, categoryId);
```suggestion
        List<Book> actual = bookRepository.findAllByCategoryId(pageable, category.getId());
```

2024-10-14 10:14 UTC, JJJazl commented on src/test/java/mate/academy/onlinebookstore/repository/BookRepositoryTest.java
> +        Long categoryId = 1L;
```suggestion
```

2024-10-14 10:14 UTC, JJJazl commented on src/test/java/mate/academy/onlinebookstore/service/BookServiceTest.java
> +        Mockito.when(bookMapper.toDto(book)).thenReturn(expected);
You can use static import for method 'when()', it will make code more clear

2024-10-14 10:14 UTC, JJJazl commented on src/test/java/mate/academy/onlinebookstore/service/BookServiceTest.java
> +        updateRequestDto.setCategoryIds(Set.of(2L));
```suggestion 
```

2024-10-14 10:14 UTC, JJJazl commented on src/test/java/mate/academy/onlinebookstore/service/BookServiceTest.java
> +                );
```suggestion
        BookSearchParametersDto searchParams = new BookSearchParametersDto();
        searchParams.setAuthors(new String[]{"author"}); 
```

2024-10-14 10:14 UTC, JJJazl commented on src/test/java/mate/academy/onlinebookstore/service/BookServiceTest.java
> +public class BookServiceTest {
Please, add 'verify()' checks for your BookServiceTest methods, like you did for CategoryServiceTest

2024-10-14 10:14 UTC, JJJazl commented on src/test/java/mate/academy/onlinebookstore/service/BookServiceTest.java
> +        Mockito.verify(bookRepository).deleteById(1L);
You have different implementations of `deleteById()` test method in `BookServiceTest` and `CategoryServiceTest` classes. Please, mock bookRepository call, as you did in `CategoryServiceTest`

2024-10-16 04:29 UTC, Leanchers commented on src/test/java/mate/academy/onlinebookstore/service/BookServiceTest.java
> +                );
it is record type

2024-10-16 13:45 UTC, Elena-Bruyako requested changes
Good job! Let's improve it

2024-10-16 13:45 UTC, Elena-Bruyako commented on src/test/java/mate/academy/onlinebookstore/config/CustomMySqlContainer.java
> +        System.out.println("Password: " + mySqlContainer.getPassword());
```suggestion
```

2024-10-16 13:45 UTC, Elena-Bruyako commented on src/test/java/mate/academy/onlinebookstore/controller/BookControllerTest.java
> +                    new ClassPathResource("database/books/add-books-to-books-table.sql")
You can use `@Sql` annotation under the test class and provide scripts
For example: 
```
@Sql(scripts = {"classpath:database/create/add-default-categories.sql",
        "classpath:database/create/add-default-books.sql",
        "classpath:database/create/add-into-books-categories-table.sql"})
```

Also, you can specify executionPhase (BEFORE_TEST_METHOD by default)

2024-10-16 13:45 UTC, Elena-Bruyako commented on src/test/java/mate/academy/onlinebookstore/controller/BookControllerTest.java
> +        Assertions.assertNotNull(actual);
use static imports (check all places)

2024-10-16 13:45 UTC, Elena-Bruyako commented on src/test/java/mate/academy/onlinebookstore/controller/BookControllerTest.java
> +    }
let's add not valid test cases

2024-10-16 13:45 UTC, Elena-Bruyako commented on src/test/java/mate/academy/onlinebookstore/repository/BookRepositoryTest.java
> +        Book book1 = new Book();
don't use numbers for naming

2024-10-17 13:29 UTC, Elena-Bruyako approved these changes

2024-12-07 14:37 UTC, merged